### ISSUE TITLE
Execute change set in other region than eu-west-1

### ISSUE THREAD

**Issue by K-Stefan** [KCOM-Enterprise/cfn-square#20]
There is an issue if you want to execute an change_set which is not in region eu-west-1.  The default region in your code is set to eu-west-1 https://github.com/KCOM-Enterprise/cfn-square/blob/d8ed243f33f3f784d944386c05cb2222eb5687b5/src/main/python/cfn_sphere/cli.py#L99 
So if you do not specific your region you run into this error: 
```
23.08.2018 15:02:49 ERROR: Could not execute change set arn:aws:cloudformation:eu-central-1:########:changeSet/test-######/#############: Does not exist
or is in an invalid state.
```

It would be nice if give a hint in your wiki that you have to set your region via argument "-r".  

The better solution would be to parse the region from the change-set ARN arn:aws:cloudformation:**eu-central-1**:########:changeSet/test-######/#############

**Comment by rayoogmy** [comment]
Hi there,

Thanks - I will have a quick look at this.
