### ISSUE TITLE
Upgrade pyyaml to version 5.3.1 or higher.

### ISSUE THREAD

**Issue by bmcoelho** [KCOM-Enterprise/cfn-square#43]
Arbitrary Code Execution
HIGH SEVERITY
Package Manager: pip
Vulnerable module: pyyaml

Overview
pyyaml is a YAML parser and emitter for Python.

Affected versions of this package are vulnerable to Arbitrary Code Execution. It is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.

Remediation
Upgrade pyyaml to version 5.3.1 or higher.

**Comment by bmcoelho** [comment]
Guys, any update on this one? 

Thanks

**Comment by AbdusSuhail-kcom** [comment]
Hi @bmcoelho . Thanks for highlighting this issue. This has now been resolved from our latest 0.3.0 release.

Please note that v0.3.0 is compatible with Python 3.6+

**Comment by bmcoelho** [comment]
Thanks @AbdusSuhail-kcom
